### ISSUE TITLE
geckodriver errror

### ISSUE THREAD

**Issue by djrose305** [ThoughtfulDev/EagleEye#109]
==> How many jitters, higher is better [max 100] (default=70): 70
==> Opening Webdriver
Traceback (most recent call last):
  File "/usr/local/bin/EagleEye/eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "/usr/local/bin/EagleEye/eagle-eye.py", line 99, in main
    f.grabData()
  File "/usr/local/bin/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
  File "/usr/local/bin/EagleEye/utils/config.py", line 45, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 160, in __init__
    self.service = Service(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/service.py", line 44, in __init__
    log_file = open(log_path, "a+") if log_path is not None and log_path != "" else None
PermissionError: [Errno 13] Permission denied: 'geckodriver.log'
┌─[✗]─[qatux@qatux]─[/usr/local/bin/EagleEye]

hey i'm having this issue with the geckodriver, seems to be working for the qrljacker so i'm not sure. do i need to change do the sudo chown root:root .Xauthority thing for this? i'm running parrot secutity, thx

**Comment by ThoughtfulDev** [comment]
Seems to be a local permission error. The docker container doesnt seem to have permission. I recommend running bare metal or adjusting the permissions.
