### ISSUE TITLE
stuck in google search

### ISSUE THREAD

**Issue by soli49** [ThoughtfulDev/EagleEye#115]
Google Reverse Image Search
==> Opening Webdriver

:: Uploading Local Known Images
Traceback (most recent call last):
  File "eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 131, in main
    g.collectLinksLocal()
  File "/home/soliman/Desktop/EagleEye/grabber/google.py", line 134, in collectLinksLocal
    elems = driver.find_elements_by_xpath(self.PHOTO_XPATH)[0]
IndexError: list index out of range

**Comment by ThoughtfulDev** [comment]
Should be fixed in latest commit.
