### ISSUE TITLE
:: Uploading Local Known Images /// someone help me?

### ISSUE THREAD

**Issue by cicadasec** [ThoughtfulDev/EagleEye#117]
:: Uploading Local Known Images
==> Please agree to google's stuff in the browser
Traceback (most recent call last):
  File "/root/tools/EagleEye/eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "/root/tools/EagleEye/eagle-eye.py", line 131, in main
    g.collectLinksLocal()
  File "/root/tools/EagleEye/grabber/google.py", line 136, in collectLinksLocal
    elems = driver.find_elements_by_xpath(self.PHOTO_XPATH)[0]
IndexError: list index out of range

**Comment by ThoughtfulDev** [comment]
Since everything was maintained manually by me and currently i dont find the time to fix it you may submit a pull request if you have time to fix those issues.

Hint: the dev tools of your browser will help you to find the correct xpath

**Comment by MasterChief220** [comment]
Did you try using another browser and changing the path in the config file to that browser.?

**Comment by ThoughtfulDev** [comment]
Check the latest commit
