### ISSUE TITLE
getting error 

### ISSUE THREAD

**Issue by Simran9769** [ThoughtfulDev/EagleEye#125]
python3 eagle-eye.py
Traceback (most recent call last):
  File "/root/EagleEye/eagle-eye.py", line 9, in <module>
    import utils.config as cfg
  File "/root/EagleEye/utils/config.py", line 8, in <module>
    cfg = json.load(json_data)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 8 column 27 (char 161)

**Comment by ThoughtfulDev** [comment]
check your  config you might have added a syntax error
