### ISSUE TITLE
ModuleNotFoundError: No module named 'requests_html'

### ISSUE THREAD

**Issue by j96693678** [ThoughtfulDev/EagleEye#126]
when I enter the command "python3 eagle-eye.py" i get the following error:
Traceback (most recent call last):
  File "eagle-eye.py", line 12, in <module>
    from grabber.instagram import InstagramGrabber
  File "/home/justkiller420/EagleEye/grabber/instagram.py", line 1, in <module>
    from requests_html import HTMLSession
ModuleNotFoundError: No module named 'requests_html'

**Comment by ThoughtfulDev** [comment]
Try using Python 3.6
