### ISSUE TITLE
Docker WSL Ubuntu 20.04 Not Working

### ISSUE THREAD

**Issue by ondrovic** [ThoughtfulDev/EagleEye#136]
Followed the documentation, there are items in the the `known` folder and I changed the name in `entry.sh`

here is the docker command I am issuing

```
sudo docker run -t --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" -v /mnt/c/users/ondro/Desktop/EagleEye/known:/EagleEye/known -v /mnt/c/users/ondro/Desktop/EagleEye/result:/result -v /mnt/c/users/ondro/Desktop/EagleEye/entry.sh:/entry.sh eagle-eye
```

with the results

```log
Traceback (most recent call last):
  File "eagle-eye.py", line 13, in <module>
    from face_recog import FaceRecog
  File "/EagleEye/face_recog.py", line 1, in <module>
    import cv2
  File "/usr/local/lib/python3.6/dist-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by ondrovic** [comment]
got that resolved by adding `ffmpeg libsm6 libxext6` to the dockerfile for the `apt-get install ` but now getting 
```
:: Running in DOCKER MODE
==> Skipping jitters since specified in config.json
==> Opening Webdriver
Traceback (most recent call last):
  File "eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 99, in main
    f.grabData()
  File "/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
  File "/EagleEye/utils/config.py", line 45, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
```
assuming that something else if missing, trying to find it

**Comment by ThoughtfulDev** [comment]
We require a valid x server i believe hence its not working. So please try using actual Ubuntu. (VM not in wsl)
