### ISSUE TITLE
Please help.... I cannot continue

### ISSUE THREAD

**Issue by tera-mithril** [ThoughtfulDev/EagleEye#138]
Hello this is what I get every time I run python3 eagle-eye.py  

==> Enter the persons name to find on FB: USER EXAMPLE
==> How many jitters, higher is better [max 100] (default=70): 50
==> Opening Webdriver
Traceback (most recent call last):
  File "/home/USER/h-toolz/EagleEye/eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "/home/USER/h-toolz/EagleEye/eagle-eye.py", line 99, in main
    f.grabData()
  File "/home/USER/h-toolz/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
  File "/home/USER/h-toolz/EagleEye/utils/config.py", line 45, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 160, in __init__
    self.service = Service(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/service.py", line 44, in __init__
    log_file = open(log_path, "a+") if log_path is not None and log_path != "" else None
PermissionError: [Errno 13] Permission denied: 'geckodriver.log'

My specs are: :::::
------------------------------------------------------------------------
OS: Kali GNU/Linux Rolling x86_64                             
Host: K55A 1.0                                                
Kernel: 5.14.0-kali4-amd64                                    
Shell: zsh 5.8                                                
DE: Xfce 4.16
WM: Xfwm4                                                     
WM Theme: Kali-Dark                                           
Terminal: qterminal                                           
Terminal Font: FiraCode 10                                    
CPU: Intel i5-3210M (4) @ 3.100GHz                            
GPU: Intel 3rd Gen Core processor Graphics Controller         
Memory: 3384MiB / 7779MiB

**Comment by ThoughtfulDev** [comment]
Installed geckodriver?

**Comment by MasterChief220** [comment]
> Installed geckodriver?

same issue and yes geckodriver is installed.
