### ISSUE TITLE
help

### ISSUE THREAD

**Issue by AlexPB05** [ThoughtfulDev/EagleEye#143]
I get this error of loading webdriver, what did I do wrong?

Traceback (most recent call last):
  File "/home/alexander/Escritorio/Github/EagleEye-master/eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "/home/alexander/Escritorio/Github/EagleEye-master/eagle-eye.py", line 99, in main
    f.grabData()
  File "/home/alexander/Escritorio/Github/EagleEye-master/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
  File "/home/alexander/Escritorio/Github/EagleEye-master/utils/config.py", line 45, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by F-Y-M** [comment]
i solved this downloading the latest version of geckodriver (in this moment is the geckodriver v0.30.0)

**Comment by MasterChief220** [comment]
> I get this error of loading webdriver, what did I do wrong?
> 
> 
> Traceback (most recent call last):
>   File "/home/alexander/Escritorio/Github/EagleEye-master/eagle-eye.py", line 229, in <module>
>     main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
>   File "/home/alexander/Escritorio/Github/EagleEye-master/eagle-eye.py", line 99, in main
>     f.grabData()
>   File "/home/alexander/Escritorio/Github/EagleEye-master/grabber/facebook.py", line 16, in grabData
>     driver = cfg.getWebDriver()
>   File "/home/alexander/Escritorio/Github/EagleEye-master/utils/config.py", line 45, in getWebDriver
>     return webdriver.Firefox(profile)
>   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
>     RemoteWebDriver.__init__(
>   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
>     self.start_session(capabilities, browser_profile)
>   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
>     response = self.execute(Command.NEW_SESSION, parameters)
>   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
> 

You need to add gecko driver and add the right path in the config file.
