### ISSUE TITLE
It does not work for me, is there a solution to this error?

### ISSUE THREAD

**Issue by ZoOoOoOoOoOom** [ThoughtfulDev/EagleEye#151]
I tried to search for Mark Zuckerberg's picture, but the following errors appeared. Can you solve this please?

- OS : Kali linux
- using Firefox ESR with Geckodriver Version 0.17.
- the Geckodriver in the same path !

`==> Enter the persons name to find on FB: Mark
==> How many jitters, higher is better [max 100] (default=70): 
==> Settings jitters to 70
==> Opening Webdriver
Traceback (most recent call last):
  File "/root/EagleEye/eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "/root/EagleEye/eagle-eye.py", line 99, in main
    f.grabData()
  File "/root/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
  File "/root/EagleEye/utils/config.py", line 45, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/firefox/webdriver.py", line 172, in __init__
    self.service.start()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 1

root@kali:~/EagleEye# 
`

https://prnt.sc/En5EFfnTq3PT

**Comment by D4nk0St0rM** [comment]
I found not running it as root, after git clone into non-sudo directory (i.e. not /opt/) so that `ls -lha` on the directory and files is `kali:kali` , it worked.

**Comment by whois00** [comment]
> I found not running it as root, after git clone into non-sudo directory (i.e. not /opt/) so that `ls -lha` on the directory and files is `kali:kali` , it worked.

Hi, I have the same error. You mean to clone whole project in root and to run it there, or somewhere outside root? Thanks.
