### ISSUE TITLE
help

### ISSUE THREAD

**Issue by haxx12** [ThoughtfulDev/EagleEye#156]
File "/home/kali/EagleEye/eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "/home/kali/EagleEye/eagle-eye.py", line 99, in main
    f.grabData()
  File "/home/kali/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
  File "/home/kali/EagleEye/utils/config.py", line 45, in getWebDriver
    return webdriver.Firefox(profile)
  File "/home/kali/.local/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 172, in __init__
    self.service.start()
  File "/home/kali/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/kali/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 1

**Comment by haxx12** [comment]
==> Enter the persons name to find on FB: kim boidn
==> How many jitters, higher is better [max 100] (default=70): 
==> Settings jitters to 70
==> Opening Webdriver
==> Please agree to facebook's stuff in the browser
Traceback (most recent call last):
  File "/home/kali/EagleEye/eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "/home/kali/EagleEye/eagle-eye.py", line 99, in main
    f.grabData()
  File "/home/kali/EagleEye/grabber/facebook.py", line 25, in grabData
    profile_img_links = driver.find_elements_by_xpath("//a[@class='_2ial']")
AttributeError: 'WebDriver' object has no attribute 'find_elements_by_xpath
