### ISSUE TITLE
executor failed running [/bin/sh -c apt-get update && add-apt-repository -y ppa:deadsnakes/ppa && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python3.6 python3.6-dev]

### ISSUE THREAD

**Issue by Drjacky** [ThoughtfulDev/EagleEye#157]
```bash
#9 5.712 Get:5 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu xenial InRelease [18.1 kB]
#9 5.862 Fetched 18.1 kB in 1s (16.4 kB/s)
#9 5.862 Reading package lists...
#9 6.699 Reading package lists...
#9 7.708 Building dependency tree...
#9 7.864 Reading state information...
#9 8.010 E: Unable to locate package python3.6
#9 8.010 E: Couldn't find any package by glob 'python3.6'
#9 8.010 E: Couldn't find any package by regex 'python3.6'
#9 8.010 E: Unable to locate package python3.6-dev
#9 8.010 E: Couldn't find any package by glob 'python3.6-dev'
#9 8.010 E: Couldn't find any package by regex 'python3.6-dev'
------
executor failed running [/bin/sh -c apt-get update && add-apt-repository -y ppa:deadsnakes/ppa && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python3.6 python3.6-dev]: exit code: 100
```

**Comment by Drjacky** [comment]
I installed it manually: https://github.com/ThoughtfulDev/EagleEye#manual-prerequisites-installation-if-you-are-hardcore

Now, I get this:
```bash
==> How many jitters, higher is better [max 100] (default=70): 100

:: Google Reverse Image Search
==> Opening Webdriver

:: Uploading Local Known Images
==> Please agree to google's stuff in the browser
Traceback (most recent call last):
  File "/EagleEye/eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "/EagleEye/eagle-eye.py", line 131, in main
    g.collectLinksLocal()
  File "/EagleEye/grabber/google.py", line 136, in collectLinksLocal
    elems = driver.find_elements_by_xpath(self.PHOTO_XPATH)[0]
AttributeError: 'WebDriver' object has no attribute 'find_elements_by_xpath'
```

**Comment by Drjacky** [comment]
> Selenium just removed that method in version 4.3.0. See the CHANGES: https://github.com/SeleniumHQ/selenium/blob/a4995e2c096239b42c373f26498a6c9bb4f2b3e7/py/CHANGES

https://stackoverflow.com/a/72754667/421467

**Comment by unnamedc** [comment]
how fix it?

**Comment by Manith-2001** [comment]
Well for me updating the image from 
```dockerfile
FROM ubuntu:16.04 
```
to
```dockerfile
FROM ubuntu:18.04 
```
fixed the issue for me

**Comment by StefanYasin** [comment]
The Dockerfile targets Python 3.6 via the deadsnakes PPA on Ubuntu xenial. Python 3.6 reached end-of-life in 2021 and the PPA dropped the packages, so this image cannot build as written. Fix it by switching the base image to a current LTS (e.g. `ubuntu:22.04` or `python:3.11-slim`) and installing `python3.11 python3.11-dev` instead. After that, only minor dependency pin tweaks should be needed. Worth knowing: the repo hasn't been touched since 2021, which is the root cause of most build failures on this project today.
