### ISSUE TITLE
EagleEye ERROR

### ISSUE THREAD

**Issue by cr4shcod3** [ThoughtfulDev/EagleEye#16]
:: Starting Face Recognition
==> Loading known faces
==> ERROR: No Face Encodings found!
==> ERROR: Did you call `loadKnown(label)` before calling this method?
Traceback (most recent call last):
  File "eagle-eye.py", line 230, in <module>
    main(skipFB=args.skipfb, skipIR=args.skipir, skipY=None, FBUrls=[])
  File "eagle-eye.py", line 88, in main
    profile_links, profile_imgs = r.getValidLinksAndImg(name)
ValueError: not enough values to unpack (expected 2, got 0)

$ uname -a
Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 GNU/Linux

$ firefox --version
Mozilla Firefox 52.9.0

'GeckoDriver Version: v0.18.0'

**Comment by cr4shcod3** [comment]
Already added pictures in known folder.

**Comment by ThoughtfulDev** [comment]
Are you sure that they are in there? My latest commit adds support for more filestypes.
Supported Filetypes are: **jpg/JPG, jpeg/JPEG, png/PNG, bmp/BMP**

**Comment by cr4shcod3** [comment]
Ok let me try it again. Thanks for the response

**Comment by cr4shcod3** [comment]
@ThoughtfulDev You can close this now. Thanks for the fix. It's now working.
For those who are using WSL. I can say to you that this tool is working on WSL
