### ISSUE TITLE
Geckodriver issue

### ISSUE THREAD

**Issue by ardar06** [ThoughtfulDev/EagleEye#162]
Traceback (most recent call last):
  File "/home/seik/EagleEye/eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "/home/seik/EagleEye/eagle-eye.py", line 99, in main
    f.grabData()
  File "/home/seik/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
  File "/home/seik/EagleEye/utils/config.py", line 45, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/firefox/webdriver.py", line 197, in __init__
    super().__init__(command_executor=executor, options=options, keep_alive=True)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

**Comment by Ma2T-Uchiha** [comment]
Same error here

**Comment by Chasefan26** [comment]
Have same error, anyone viewing this have fix for it?
