### ISSUE TITLE
Stuck at opening webdriver

### ISSUE THREAD

**Issue by Jaymzu** [ThoughtfulDev/EagleEye#17]
when launching eagleeye, it seems to get stuck at "opening webdriver". 
- path to geckodriver is specified in config.json
- It does open a firefox window
- there are 2 jpg files in the known folder
- after about a minute it ends up dying 
`==> Opening Webdriver
Traceback (most recent call last):
  File "eagle-eye.py", line 230, in <module>
    main(skipFB=args.skipfb, skipIR=args.skipir, skipY=None, FBUrls=[])
  File "eagle-eye.py", line 84, in main
    f.grabData()
  File "/root/tmp/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
  File "/root/tmp/EagleEye/utils/config.py", line 40, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused
`

**Comment by ThoughtfulDev** [comment]
Could be a Version mismatch between your Firefox and the Geckodriver. (e.g on Kali)

Check your `geckodriver.log` file (should be in the same directory as python file) 
Please post the content here.

**Comment by Jaymzu** [comment]
[geckodriver.log](https://github.com/ThoughtfulDev/EagleEye/files/2159505/geckodriver.log)

And yes. I'm running it on Kali.

**Comment by ThoughtfulDev** [comment]
Excerpt from the README: **Note: If you are using Firefox ESR(like Kali does) please use the Geckodriver Version 17**

You are using Version 21
`1530624566068	geckodriver	INFO	geckodriver 0.21.0`

**Comment by Jaymzu** [comment]
yeah, my bad. Sorry for the false alarm.

**Comment by ThoughtfulDev** [comment]
Since the Problem seems fixed :+1: 
closed.
