### ISSUE TITLE
AttributeError: 'FirefoxProfile' object has no attribute 'capabilities'

### ISSUE THREAD

**Issue by orangeyichengyu** [ThoughtfulDev/EagleEye#170]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/common/selenium_manager.py", line 87, in driver_location
    browser = options.capabilities["browserName"]
              ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FirefoxProfile' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/EagleEye/eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "/root/EagleEye/eagle-eye.py", line 99, in main
    f.grabData()
  File "/root/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
             ^^^^^^^^^^^^^^^^^^
  File "/root/EagleEye/utils/config.py", line 45, in getWebDriver
    return webdriver.Firefox(profile)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/firefox/webdriver.py", line 59, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/common/driver_finder.py", line 40, in get_path
    msg = f"Unable to obtain driver for {options.capabilities['browserName']} using Selenium Manager."
                                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FirefoxProfile' object has no attribute 'capabilities'

**Comment by aygupt1822** [comment]
Inside config.py from utils/config.py :-

replace :-
`profile = webdriver.FirefoxProfile()`

With :-
`profile = webdriver.FirefoxOptions()`

and then try, maybe it will fix your issue.

**Comment by orangeyichengyu** [comment]
> Inside config.py from utils/config.py :-
> 
> replace :- `profile = webdriver.FirefoxProfile()`
> 
> With :- `profile = webdriver.FirefoxOptions()`
> 
> and then try, maybe it will fix your issue.

Ye it just worked. Thank you so much! In my understanding, it is just a version error right?

**Comment by orangeyichengyu** [comment]
> Inside config.py from utils/config.py :-
> 
> replace :- `profile = webdriver.FirefoxProfile()`
> 
> With :- `profile = webdriver.FirefoxOptions()`
> 
> and then try, maybe it will fix your issue.

Also I got this: 
Traceback (most recent call last):
  File "/root/EagleEye/eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "/root/EagleEye/eagle-eye.py", line 99, in main
    f.grabData()
  File "/root/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
             ^^^^^^^^^^^^^^^^^^
  File "/root/EagleEye/utils/config.py", line 45, in getWebDriver
    return webdriver.Firefox(profile)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/firefox/webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

**Comment by aygupt1822** [comment]
I honestly gave up on this repo. There have been soo many bugs and errors, they occur in endless loop even after you resolve them.

**Comment by richdear** [comment]
Somebody fork this repo and rewrite in golang or rust!

**Comment by pac-source** [comment]
Hey guys, I am getting something similar. 
```
Traceback (most recent call last):
  File "/EagleEye/eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "/EagleEye/eagle-eye.py", line 99, in main
    f.grabData()
  File "/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
  File "/EagleEye/utils/config.py", line 45, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/firefox/webdriver.py", line 57, in __init__
    if finder.get_browser_path():
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/driver_finder.py", line 47, in get_browser_path
    return self._binary_paths()["browser_path"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/driver_finder.py", line 56, in _binary_paths
    browser = self._options.capabilities["browserName"]
AttributeError: 'FirefoxProfile' object has no attribute 'capabilities'
```
I tried this though, Still it doesn't seem to work

> Inside config.py from utils/config.py :-
> 
> replace :- `profile = webdriver.FirefoxProfile()`
> 
> With :- `profile = webdriver.FirefoxOptions()`
> 
> and then try, maybe it will fix your issue.

I am getting the same error over and over again. By the way I am using `ubuntu:22.04` as the **dockerimage**. 

Help appreciated,
**Thanks in advance**.

**Comment by StefanYasin** [comment]
Diagnosis: this is Selenium 4 vs 3 API breakage. The code builds a `FirefoxProfile` and passes it where Selenium 4 requires a `FirefoxOptions` object - `options.capabilities` does not exist on the old profile object. Two fixes:

1. Quickest for this legacy code path: `pip install selenium==3.141.0` (the code was written against Selenium 3).
2. Or migrate: use `FirefoxOptions`, set `opts.profile = FirefoxProfile(path)`, then `webdriver.Firefox(options=opts)`, and use `opts.set_capability(...)` wherever capabilities were being set. If you go Selenium 4.6+, make sure geckodriver is reachable (Selenium Manager handles that automatically).

The root cause: this repo has not been updated since 2021, so it is pinned to dependencies that no longer match modern versions.
