### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by peterlymo** [ThoughtfulDev/EagleEye#19]
try to use the tool after a 20 minutes struggle because of using automatically installation which did nothing then return to manually and finally made it,,

so i run the tool and start to search but later there some error happen
see the ss

![screenshot from 2018-07-03 21-29-42](https://user-images.githubusercontent.com/30964644/42238320-21a5a21a-7f09-11e8-8951-146970bb53ba.png)

**Comment by ThoughtfulDev** [comment]
Does the Browser open? Does the Browser navigate to google.com/imghp ?

Seems like the Browser is closed when it tries to find the DOM Element.

**Comment by aNaoy** [comment]
I have the exact same issue.

The browser is well opened and access to google.com/imghp.

I can see it starting the searches but after a few seconds (when it found the results for the picture I put in ./known), I have this error, EagleEye exits but not Firefox.

**Comment by ThoughtfulDev** [comment]
i Tried using the latest Geckodriver (Ver 0.21.0) and FF 60.0.2, everything works. No crashes.
**Note: If you are using Firefox ESR(like Kali does) please use the Geckodriver Version 17**

**Comment by gskornowicz** [comment]
I'm also having this issue.
Linux Mint 19
Firefox 60.0.2
Geckodriver 0.21.0

Also i had a bit of trouble to get this script to even start.
`:: Google Reverse Image Search
==> Opening Webdriver

:: Uploading Local Known Images
  -> Inserting Path
Traceback (most recent call last):
  File "eagle-eye.py", line 230, in <module>
    main(skipFB=args.skipfb, skipIR=args.skipir, skipY=None, FBUrls=[])
  File "eagle-eye.py", line 116, in main
    g.collectLinksLocal()
  File "/home/mint/EagleEye/grabber/google.py", line 94, in collectLinksLocal
    pred = driver.find_element_by_xpath("/html/body/div[6]/div[3]/div[3]/div[1]/div[2]/div/div[2]/div[1]/div/div[2]/a")
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 393, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 966, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/remote_connection.py", line 472, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/remote_connection.py", line 495, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe
`

**Comment by gskornowicz** [comment]
It worked when i changed geckodriver  to 0.19.1 :)
