### ISSUE TITLE
Broken Pipe no matter of the geckodriver

### ISSUE THREAD

**Issue by thistehneisen** [ThoughtfulDev/EagleEye#22]
I'm on Linux ParrotSec with Firefox Quantum (61.0, 64-bit), tried the systems geckodriver, tried 0.19.1, 0.17, all return the same result:

```
:: Uploading Local Known Images
  -> Inserting Path
Traceback (most recent call last):
  File "eagle-eye.py", line 230, in <module>
    main(skipFB=args.skipfb, skipIR=args.skipir, skipY=None, FBUrls=[])
  File "eagle-eye.py", line 116, in main
    g.collectLinksLocal()
  File "/home/nils/Code/Python/EagleEye/grabber/google.py", line 94, in collectLinksLocal
    pred = driver.find_element_by_xpath("/html/body/div[6]/div[3]/div[3]/div[1]/div[2]/div/div[2]/div[1]/div/div[2]/a")
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 393, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 966, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/remote_connection.py", line 472, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/remote_connection.py", line 495, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by ThoughtfulDev** [comment]
I'm not able to reproduce this Issue (since it popped up 3 times already).
Did you try only 0.17 and 0.19? Please just try the most recent version(0.21.0).
You can also try to increase the `SLEEP_DELAY` in the `config.json` file.

Please report back since i havent seen this Error, neither on a physical machine(ubuntu 16.04, arch) nor on a VM (ubuntu 16.04)

**Comment by thistehneisen** [comment]
My guess is that it could be related that Firefox version is Quantum? I did try the most recent version of webdriver also, same results.

**Comment by Bechma** [comment]
I faced the same issue when I ran the script in VirtualBox with Ubuntu 18.04 (fresh install)

> Linux user-VirtualBox 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ThoughtfulDev** [comment]
I myself use Firefox 61.0 and driver 0.21.0 works fine. I will try to test it with a fresh VM. But for now i have no Idea... i will test things out and report back.

**Comment by pierreke77** [comment]
Traceback (most recent call last):
  File "eagle-eye.py", line 230, in <module>
    main(skipFB=args.skipfb, skipIR=args.skipir, skipY=None, FBUrls=[])
  File "eagle-eye.py", line 116, in main
    g.collectLinksLocal()
  File "/home/osint/EagleEye/grabber/google.py", line 94, in collectLinksLocal
    pred = driver.find_element_by_xpath("/html/body/div[6]/div[3]/div[3]/div[1]/div[2]/div/div[2]/div[1]/div/div[2]/a")
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 393, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 966, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/remote_connection.py", line 472, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/remote_connection.py", line 495, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

Fresh VM, Xubunti v18 ....

**Comment by ThoughtfulDev** [comment]
@pierreke77 could you try ubuntu 16.04 (since this is what i tested it with).

I'm really lost on this error...

**Comment by cr4shcod3** [comment]
https://github.com/mozilla/geckodriver/releases - Check this for the appropriate geckodriver version

**Comment by ThoughtfulDev** [comment]
The latest commit should fix this issue regardless the Geckodriver Version.
