### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by roozea** [ThoughtfulDev/EagleEye#23]
I'm in Kali 32 bit and Geckodriver 21, help me please!!
> Traceback (most recent call last):
  File "eagle-eye.py", line 230, in <module>
    main(skipFB=args.skipfb, skipIR=args.skipir, skipY=None, FBUrls=[])
  File "eagle-eye.py", line 84, in main
    f.grabData()
  File "/root/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
  File "/root/EagleEye/utils/config.py", line 40, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by ThoughtfulDev** [comment]
Seems  like a architecture issue. did you choose the right geckodriver arch(32bit)?

I really recommend that you use the 64bit Version of Kali.

**Comment by roozea** [comment]
I'm on Kali 32 bits and my geckodriver 32 bits but i'm downgrade geckodriver and work's
You're the best!!
