### ISSUE TITLE
Import error . Probably a problem that is related to my setup...

### ISSUE THREAD

**Issue by pierreke77** [ThoughtfulDev/EagleEye#25]
Traceback (most recent call last):
  File "eagle-eye.py", line 15, in <module>
    from grabber.instagram import InstagramGrabber
  File "/home/osint/EagleEye/grabber/instagram.py", line 1, in <module>
    from requests_html import HTMLSession
  File "/usr/local/lib/python3.5/dist-packages/requests_html.py", line 6, in <module>
    import pyppeteer
  File "/usr/local/lib/python3.5/dist-packages/pyppeteer/__init__.py", line 25, in <module>
    from pyppeteer.launcher import connect, launch, executablePath  # noqa: E402
  File "/usr/local/lib/python3.5/dist-packages/pyppeteer/launcher.py", line 19, in <module>
    from pyppeteer.browser import Browser
  File "/usr/local/lib/python3.5/dist-packages/pyppeteer/browser.py", line 11, in <module>
    from pyppeteer.target import Target
  File "/usr/local/lib/python3.5/dist-packages/pyppeteer/target.py", line 7, in <module>
    from typing import Any, Callable, Coroutine, Dict, List, Optional
ImportError: cannot import name 'Coroutine'

**Comment by ThoughtfulDev** [comment]
Coroutine is only available in the Typing package which ships with Python 3.6+
see [Here](https://stackoverflow.com/questions/44651115/python-typing-module-missing-the-coroutine-class-in-python-3-5) and [Here](https://pypi.org/project/typing/)

As stated in the README at the top (the badge) only Python Version 3.6+ was tested by me and is supported.

So i suggest that you upgrade your python version to the newest 3.6 version.
