### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by DNM-3** [ThoughtfulDev/EagleEye#26]
Hi there,

I have some errors when I enter this command: `python3 eagle-eye.py `
Errors:
```
Traceback (most recent call last):
  File "eagle-eye.py", line 15, in <module>
    from grabber.instagram import InstagramGrabber
  File "/home/work/EagleEye/grabber/instagram.py", line 1, in <module>
    from requests_html import HTMLSession
  File "/usr/local/lib/python3.5/dist-packages/requests_html.py", line 419
    element=PyQuery(html)('html') or PyQuery(f'<html>{html}</html>')('html'),
                                                                  ^
SyntaxError: invalid syntax
```
What could the problem be?

**Comment by ThoughtfulDev** [comment]
Check Issue #18
