### ISSUE TITLE
Index Error on Reverse Image Search

### ISSUE THREAD

**Issue by cr4shcod3** [ThoughtfulDev/EagleEye#28]
:: ImageRaider Reverse Image Search
==> Opening Webdriver
  -> Inserting <img>
  -> Inserting <img>
  -> Inserting <img>
  -> Inserting <img>
  -> Submitting...
Traceback (most recent call last):
  File "eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, skipIR=args.skipir, skipY=None, FBUrls=[])
  File "eagle-eye.py", line 152, in main
    raider.insertImageLinks(raider_img_list)
  File "/home/user/tools/searcher/EagleEye/grabber/imageraider.py", line 33, in insertImageLinks
    btn = self.driver.find_elements_by_xpath('/html/body/div[3]/div/div/article/div/div[1]/form/span/input')[0]
IndexError: list index out of range

Python Version 3.6.6

**Comment by ThoughtfulDev** [comment]
Should be fixed now.

**Comment by checkymander** [comment]
Running the most recent version, and I still seem to be getting this error. Running on Kali and get the following error.

:: Uploading Local Known Images
Traceback (most recent call last):
  File "eagle-eye.py", line 254, in <module>
    main(skipFB=args.skipfb, skipIR=args.skipir, skipY=None, FBUrls=[], jsonRep=jsonRepFile)
  File "eagle-eye.py", line 124, in main
    g.collectLinksLocal()
  File "/root/EagleEye/grabber/google.py", line 109, in collectLinksLocal
    elems = driver.find_elements_by_xpath('//*[@id="qbi"]')[0]
IndexError: list index out of range

**Comment by ThoughtfulDev** [comment]
I will investigate this, if i find the time.

**Comment by Palmus84** [comment]
Same: IndexError: list index out of range.

**Comment by ThoughtfulDev** [comment]
Should be fixed now.

**Comment by phonemyatnaing928** [comment]
raceback (most recent call last):
File "eagle-eye.py", line 261, in
main(skipFB=args.skipfb, skipY=args.skipyandex, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
File "eagle-eye.py", line 139, in main
yandex.collectLinksLocal()
File "/root/Desktop/TOOLS/Socialvector/EagleEye/grabber/yandex.py", line 74, in collectLinksLocal
elems = driver.find_elements_by_xpath('/html/body/div[1]/div[2]/div[1]/div[1]/div[1]/div/div/div/div[1]/div[2]/form/div[1]/span/span[2]')[0]
IndexError: list index out of range

I have this error on eagle eye how do i fix this??

**Comment by mikefitzhugh** [comment]
Still waiting for fix for this.....

Traceback (most recent call last):
  File "eagle-eye.py", line 261, in <module>
    main(skipFB=args.skipfb, skipY=args.skipyandex, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 132, in main
    g.collectLinksLocal()
  File "/root/EagleEye/grabber/google.py", line 118, in collectLinksLocal
    elems = driver.find_elements_by_xpath('/html/body/div/div[3]/div[3]/form/div[2]/div/div[1]/div/div[2]/div')[0]
IndexError: list index out of range
