### ISSUE TITLE
This error gives me even if I change the version of geckodriver ( I'm using Kali and Parrot sc in virtualbox)

### ISSUE THREAD

**Issue by Elliot845** [ThoughtfulDev/EagleEye#30]
==> Enter the persons name to find on FB: Name persona
==> How many jitters, higher is better [max 100]: 50
==> Opening Webdriver
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, skipIR=args.skipir, skipY=None, FBUrls=[])
  File "eagle-eye.py", line 83, in main
    f.grabData()
  File "/root/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
  File "/root/EagleEye/utils/config.py", line 40, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 160, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable may have wrong permissions. 

![kali](https://user-images.githubusercontent.com/34638855/42981835-96ffc7cc-8b9b-11e8-9011-291e9498c3a3.PNG)

![parrot s](https://user-images.githubusercontent.com/34638855/42981840-9ab80df2-8b9b-11e8-95ad-9955ab0ab630.PNG)

**Comment by ThoughtfulDev** [comment]
Make your geckodriver executable:
`sudo chmod +x /path/to/geckodriver`

**Comment by Elliot845** [comment]
I already made it executable but still the same, some other solution?

**Comment by ThoughtfulDev** [comment]
Try `chmod 777 <path/to/geckodriver>` just for testing.
I know that this is not very safe but its just the geckodriver.
