### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: connection refused

### ISSUE THREAD

**Issue by corelanc0d3r** [ThoughtfulDev/EagleEye#34]
Hi,

I'm getting an error when trying to run EagleEye
(replaced the persons name with XXXX)

```==> Enter the persons name to find on FB: XXXX
==> How many jitters, higher is better [max 100]: 100
==> Opening Webdriver
Traceback (most recent call last):
  File "eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, skipIR=args.skipir, skipY=None, FBUrls=[])
  File "eagle-eye.py", line 83, in main
    f.grabData()
  File "/tools/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
  File "/tools/EagleEye/utils/config.py", line 40, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused
```
(firefox launches, nothing seems to happen, eventually eagle-eye dies)

config.json:
```{
    "DEFAULTS": {
        "SLEEP_DELAY": "7",
        "GOOGLE_IMG_PAGES": "3"
    },
    "WEBDRIVER": {
        "ENGINE": "firefox",
        "PATH": "/usr/bin/geckodriver"
    },
    "FILTER": [
        "instagram.com",
        "twitter.com",
        "pinterest.com",
        "plus.google.com"
    ],
    "INSTA_VALIDATION_MAX_IMAGES": "5"
}```


geckodriver
```ls -al /usr/bin/geckodriver 
-rwxr-xr-x 1 root root 10362394 Jul 31 08:30 /usr/bin/geckodriver
```

testing/running geckodriver
```/usr/bin/geckodriver 
1533019483602	geckodriver	INFO	geckodriver 0.21.0
1533019483615	geckodriver	INFO	Listening on 127.0.0.1:4444
```

Environment:
Kali (up to date) running in Virtualbox
```uname -a
Linux XXXXX 4.17.0-kali1-amd64 #1 SMP Debian 4.17.8-1kali1 (2018-07-24) x86_64 GNU/Linux
```

please kindly let me know what I did wrong, or how I can help to troubleshoot the issue
thanks

**Comment by ThoughtfulDev** [comment]
Have a look at Issue #17

**Comment by corelanc0d3r** [comment]
you're right, geckodriver version issue, it works with v0.17 indeed
