### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by devil67** [ThoughtfulDev/EagleEye#42]
python3 eagle-eye.py 
Traceback (most recent call last):
  File "eagle-eye.py", line 15, in <module>
    from grabber.instagram import InstagramGrabber
  File "/dragon/desktop/EagleEye/grabber/instagram.py", line 1, in <module>
    from requests_html import HTMLSession
  File "/usr/local/lib/python3.5/dist-packages/requests_html.py", line 419
    element=PyQuery(html)('html') or PyQuery(f'<html>{html}</html>')('html'),
                                                                  ^
SyntaxError: invalid syntax

**Comment by ThoughtfulDev** [comment]
`requests-html` only supports Python 3.6 or higher.
Try using Python 3.6+
