### ISSUE TITLE
error running python3 eagle-eye.py

### ISSUE THREAD

**Issue by glaucobonomo** [ThoughtfulDev/EagleEye#46]
hello, i installed all compunents and if i run the script it says

Traceback (most recent call last):
  File "eagle-eye.py", line 9, in <module>
    import utils.config as cfg
  File "/home/lupintheman/Documenti/tools/EagleEye/utils/config.py", line 8, in <module>
    cfg = json.load(json_data)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 15 column 2 (char 297)

specifying python3.7 i get 

Traceback (most recent call last):
  File "eagle-eye.py", line 9, in <module>
    import utils.config as cfg
  File "/home/lupintheman/Documenti/tools/EagleEye/utils/config.py", line 5, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

moved selenium in 3.7 folder and run again, i get the same result as the first i wrote here...
what should i do?

**Comment by ThoughtfulDev** [comment]
First you are using python3.6 (see the error - /usr/lib/python3.6/json...)
So use the python3.6 binary and the corresponding pip version e.g pip3.6
regarding your first error. Seems like you have messed up the config.json. Please show the config.json
