### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by Sm03leBr00t** [ThoughtfulDev/EagleEye#56]
I just started EagleEye ( I got activated :D ) and it threw the Traceback after inserting Name and Jitter

```
Traceback (most recent call last):
  File "./eagle-eye.py", line 239, in <module>
    main(skipFB=args.skipfb, skipY=args.skipyandex, FBUrls=[], jsonRep=jsonRepFile)
  File "./eagle-eye.py", line 91, in main
    f.grabData()
  File "/home/alex/Audit/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
  File "/home/alex/Audit/EagleEye/utils/config.py", line 40, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: newSession

```

**Comment by ThoughtfulDev** [comment]
Have you changed the path in config.json to the geckodriver and installed firefox and the newest geckodriver?

**Comment by Sm03leBr00t** [comment]
I actually installed Geckodriver in the already configured path and yes I do have fire fox

**Comment by ThoughtfulDev** [comment]
Which distro are you using? I tested it with a Ubuntu 16.04 VM.
Please try a Ubuntu 16.04 VM.

Sry for the late answer.
