### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by deadfishhackers** [ThoughtfulDev/EagleEye#65]
root@anonymous:~/EagleEye# python3 eagle-eye.py 
Traceback (most recent call last):
  File "eagle-eye.py", line 14, in <module>
    from grabber.instagram import InstagramGrabber
  File "/root/EagleEye/grabber/instagram.py", line 1, in <module>
    from requests_html import HTMLSession
  File "/usr/local/lib/python3.7/dist-packages/requests_html.py", line 9, in <module>
    import pyppeteer
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/__init__.py", line 30, in <module>
    from pyppeteer.launcher import connect, launch, executablePath  # noqa: E402
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/launcher.py", line 24, in <module>
    from pyppeteer.browser import Browser
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/browser.py", line 13, in <module>
    from pyppeteer.connection import Connection
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/connection.py", line 12, in <module>
    import websockets
  File "/usr/local/lib/python3.7/dist-packages/websockets/__init__.py", line 3, in <module>
    from .client import *
  File "/usr/local/lib/python3.7/dist-packages/websockets/client.py", line 12, in <module>
    from .protocol import CONNECTING, OPEN, WebSocketCommonProtocol
  File "/usr/local/lib/python3.7/dist-packages/websockets/protocol.py", line 17, in <module>
    from .compatibility import asyncio_ensure_future
  File "/usr/local/lib/python3.7/dist-packages/websockets/compatibility.py", line 9
    asyncio_ensure_future = asyncio.async           # Python < 3.5
                                        ^
SyntaxError: invalid syntax

**Comment by ThoughtfulDev** [comment]
Use python 3.6. since python 3.7 has some issues regarding the async keyword.
