### ISSUE TITLE
docker Issues can't fix it.

### ISSUE THREAD

**Issue by qqbbpsy** [ThoughtfulDev/EagleEye#73]
hello, i have already install all requirements and **i am able to use "sudo python3 eagly-eye.py"**
but i miss a step **i can't do "sudo docker build -t eagle-eye - < dockerfile" when i use this commad tell me "sudo: docker: command not found"** i have use "sudo apt get install docker" but no fix it, i have make the "know" folder and the "result" folder into "EaglyEye folder" and i have drop the know person image in it and also i have edit "entry.sh" with know persons name and next i get.. 

Opening Webdriver
Traceback (most recent call last):
  File "eagle-eye.py", line 261, in <module>
    main(skipFB=args.skipfb, skipY=args.skipyandex, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 100, in main
    f.grabData()
  File "/home/psyqq/Desktop/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
  File "/home/psyqq/Desktop/EagleEye/utils/config.py", line 43, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by ThoughtfulDev** [comment]
if docker is not find try installing it using [this tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04). dont use the docker version shipped with the default ubuntu repo.
