### ISSUE TITLE
list index out of range in docker container

### ISSUE THREAD

**Issue by loveallbuttrustafew** [ThoughtfulDev/EagleEye#76]
```
Traceback (most recent call last):
  File "eagle-eye.py", line 261, in <module>
    main(skipFB=args.skipfb, skipY=args.skipyandex, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 129, in main
    g.collectLinks(img)
  File "/EagleEye/grabber/google.py", line 41, in collectLinks
    elems = driver.find_elements_by_xpath(self.PHOTO_XPATH)[0]
IndexError: list index out of range
```

How do i fix it ?

**Comment by ArthurJrn** [comment]
Hi ! Similar issue for me: 

:: Uploading Local Known Images
Traceback (most recent call last):
  File "eagle-eye.py", line 261, in <module>
    main(skipFB=args.skipfb, skipY=args.skipyandex, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 132, in main
    g.collectLinksLocal()
  File "/EagleEye/grabber/google.py", line 122, in collectLinksLocal
    elems = driver.find_elements_by_xpath(self.PHOTO_XPATH)[0]
IndexError: list index out of range

Thanks for your time

**Comment by ThoughtfulDev** [comment]
Seems like the google webpage has changed. I'll fix when i get time.

**Comment by loveallbuttrustafew** [comment]
Fix yandex, same

**Comment by ArthurJrn** [comment]
SImilar error in Yandex: 

Traceback (most recent call last):
  File "eagle-eye.py", line 261, in <module>
    main(skipFB=args.skipfb, skipY=args.skipyandex, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 139, in main
    yandex.collectLinksLocal()
  File "/EagleEye/grabber/yandex.py", line 74, in collectLinksLocal
    elems = driver.find_elements_by_xpath('/html/body/div[1]/div[2]/div[1]/div[1]/div[1]/div/div/div/div[1]/div[2]/form/div[1]/span/span[2]')[0]
IndexError: list index out of range

**Comment by ThoughtfulDev** [comment]
As i said in other issues. Please skip yandex for now or fix It yourself.
