### ISSUE TITLE
using docker: selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette

### ISSUE THREAD

**Issue by dummys** [ThoughtfulDev/EagleEye#77]
Hello,
got this error using latest version under docker:

:: Running in DOCKER MODE
==> Skipping jitters since specified in config.json
==> Opening Webdriver
Traceback (most recent call last):
  File "eagle-eye.py", line 261, in <module>
    main(skipFB=args.skipfb, skipY=args.skipyandex, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 100, in main
    f.grabData()
  File "/EagleEye/grabber/facebook.py", line 17, in grabData
    driver.get(self.url)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette

**Comment by ilyasse005** [comment]
Hello Egele Eye i was install everything corectery but the serch not comleted way ? i have this errors 
:: Google Reverse Image Search
==> Opening Webdriver

:: Uploading Local Known Images
  -> Inserting Path
  -> Collecting Links...(Page 1)
  -> No Links found
  -> Switching to Page 2
  -> Collecting Links...(Page 2)
  -> Switching to Page 3
  -> Collecting Links...(Page 3)

:: Yandex Reverse Image Search
==> Opening Webdriver
==> Uploading Local Images
  -> Inserting Image URL
Traceback (most recent call last):
  File "eagle-eye.py", line 261, in <module>
    main(skipFB=args.skipfb, skipY=args.skipyandex, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 139, in main
    yandex.collectLinksLocal()
  File "/root/EagleEye/grabber/yandex.py", line 74, in collectLinksLocal
    elems = driver.find_elements_by_xpath('/html/body/div[1]/div[2]/div[1]/div[1]/div[1]/div/div/div/div[1]/div[2]/form/div[1]/span/span[2]')[0]
IndexError: list index out of range

**Comment by ThoughtfulDev** [comment]
Yandex is broken. Please disable it with `--skipyandex`

as for the docker error. i really have no idea. i could not reproduce that.
