### ISSUE TITLE
 Message: invalid argument: can't kill an exited process

### ISSUE THREAD

**Issue by Advogate** [ThoughtfulDev/EagleEye#86]
Traceback (most recent call last):
  File "eagle-eye.py", line 228, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 98, in main
    f.grabData()
  File "/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
  File "/EagleEye/utils/config.py", line 45, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process

**Comment by ThoughtfulDev** [comment]
Try changing the `SLEEP_DELAY` in config to a higher value and try again. Seems like the process is closed but the code still tries to close it.
