### ISSUE TITLE
Is there a mistake?

### ISSUE THREAD

**Issue by arcillus** [ThoughtfulDev/EagleEye#87]
Traceback (most recent call last):
File "eagle-eye.py", line 12, in
from grabber.instagram import InstagramGrabber
File "/root/EagleEye/grabber/instagram.py", line 1, in
from requests_html import HTMLSession
ModuleNotFoundError: No module named 'requests_html'

What should I do?

**Comment by ThoughtfulDev** [comment]
Did you install the requirements using pip?
