### ISSUE TITLE
Error 'newSession' when using normally.

### ISSUE THREAD

**Issue by Z3R0C1PH3R** [ThoughtfulDev/EagleEye#90]
Hi, I am getting an error 'newSession' when i run eagle-eye.py
I am using Kali linux, firefox quantum 66.6 (firefox-esr), geckodriver v0.17. all the packages are updated

Here is the error msg-

                                                           
`==> Skipping FB Search
==> How many jitters, higher is better [max 100] (default=70): 
==> Settings jitters to 70
:: Google Reverse Image Search
==> Opening Webdriver
Traceback (most recent call last):
  File "eagle-eye.py", line 228, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 125, in main
    g = GoogleGrabber()
  File "/home/aryan/Desktop/EagleEye/grabber/google.py", line 34, in __init__
    self.driver = cfg.getWebDriver()
  File "/home/aryan/Desktop/EagleEye/utils/config.py", line 45, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: newSession `

Please help me, thank you

**Comment by ThoughtfulDev** [comment]
Have you once tried to use the newest firefox version along with the newest geckodriver?

**Comment by Z3R0C1PH3R** [comment]
Yes, I have tried to use the latest geckodriver with latest firefox, geckodriver 0.17 with latest firefox, old firefox with geckodriver 0.17, and Old firefox with latest geckodriver, All have errors.

**Comment by ThoughtfulDev** [comment]
Maybe its a Kali Issue. Try using plain Ubuntu once.

**Comment by Z3R0C1PH3R** [comment]
It works now, after you fixed #92, as I was having the same error when using the new version of geckodriver. The geckodriver0.17  didnt work in my Kali linux machine, so you might want to change the README.md

**Comment by Z3R0C1PH3R** [comment]
Thanks😊

**Comment by Z3R0C1PH3R** [comment]
Thanks😊
