### ISSUE TITLE
please help me to fix this

### ISSUE THREAD

**Issue by MrNerDD** [ThoughtfulDev/EagleEye#91]
when i paste docker file in /usr/bin  i am getting this error and before pasting docker file in usr bin terminal was giving error of docker file missing plz help..

==> How many jitters, higher is better [max 100] (default=70): 
==> Settings jitters to 70
==> Opening Webdriver
Traceback (most recent call last):
  File "eagle-eye.py", line 228, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 98, in main
    f.grabData()
  File "/root/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
  File "/root/EagleEye/utils/config.py", line 45, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by ThoughtfulDev** [comment]
What do you mean by placing it in /usr/bin?
Have you followed the instructions here? https://github.com/ThoughtfulDev/EagleEye#docker-preferred
