### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by CybernetiX-S3C** [ThoughtfulDev/EagleEye#92]
=> Enter the persons name to find on FB: B**** L****
==> How many jitters, higher is better [max 100] (default=70): 100
==> Opening Webdriver
  -> Collecting Image URLs...(Page 1)

:: Starting Face Recognition
==> Loading known faces
  -> Loading FB_IMG_1587794265218.jpg
  -> Loading FB_IMG_1587794219598.jpg
  -> Loading FB_IMG_1587793965099.jpg
  -> Loading FB_IMG_1587793774054.jpg
  -> Loading FB_IMG_1587793830202.jpg

:: Analyzing
==> Storing Image in /tmp/user/0/PEQ936.jpg
==> Analyzing https://scontent-lax3-2.xx.fbcdn.net/v/t1.0-1/cp0/c0.0.74.74a/p74x74/32378551_127006884840...
==> Analyzing https://scontent-lax3-2.xx.fbcdn.net/v/t1.30497-1/cp0/c22.0.74.74a/p74x74/84241059_1891321...
==> Analyzing https://scontent-lax3-2.xx.fbcdn.net/v/t1.30497-1/cp0/c22.0.74.74a/p74x74/84241059_1891321...
==> Analyzing https://scontent-lax3-1.xx.fbcdn.net/v/t1.0-1/cp0/p74x74/11350406_1102410083119203_6319370...
==> Removing /tmp/user/0/PEQ936.jpg

:: Result
==> Found the following Profiles:

:: Google Reverse Image Search
==> Opening Webdriver

:: Uploading Local Known Images
Traceback (most recent call last):
  File "./eagle-eye.py", line 228, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "./eagle-eye.py", line 130, in main
    g.collectLinksLocal()
  File "/root/EagleEye/grabber/google.py", line 135, in collectLinksLocal
    elems.click()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <span class="lBbtTb z1asCe rzyADb"> could not be scrolled into view

**Comment by ThoughtfulDev** [comment]
Fixed in latest commit.
