### ISSUE TITLE
 Message: invalid argument: can't kill an exited process

### ISSUE THREAD

**Issue by disoardi** [ThoughtfulDev/EagleEye#94]
I tried to run the program but I have this error:
`==> Skipping FB Search
==> Skipping jitters since specified in config.json

:: Google Reverse Image Search
==> Opening Webdriver
Traceback (most recent call last):
  File "eagle-eye.py", line 228, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 125, in main
    g = GoogleGrabber()
  File "/EagleEye/grabber/google.py", line 34, in __init__
    self.driver = cfg.getWebDriver()
  File "/EagleEye/utils/config.py", line 45, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
`

I am using docker as specified in the README file. I attach the command and how I changed the entry.sh

`docker run -t --net=host --env="DISPLAY" --volume="$HOME/OneDrive/Progetti/EagleEye/.auth.file:/root/.Xauthority:rw" -v $HOME/Progetti/personOfInterest/known:/EagleEye/known -v $HOME/Progetti/personOfInterest/result:/result -v $HOME/OneDrive/Progetti/EagleEye/entry.sh:/entry.sh eagle-eye`

In the $HOME/Progetti/personOfInterest/known directory I put a picture in jpg format.

**Comment by ThoughtfulDev** [comment]
Have a look at #66 and #86 
Try not to run as root.
