### ISSUE TITLE
geckodriver problem;how to solve plz help

### ISSUE THREAD

**Issue by mamun626** [ThoughtfulDev/EagleEye#97]
==> Enter the persons name to find on FB: bjbjb
==> How many jitters, higher is better [max 100] (default=70): 20
==> Opening Webdriver
Traceback (most recent call last):
  File "eagle-eye.py", line 228, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 98, in main
    f.grabData()
  File "/home/kali/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
  File "/home/kali/EagleEye/utils/config.py", line 45, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by waraga2** [comment]
Had a similar issue, i downloaded kali linux, i ran it in a virtual machine, then used the autoinstall script provided by in the README.md, make sure to execute it in a non-root terminal and solved that issue.
May you should reinstall EagleEye with the autoinstall script, before trying it on a clean linux os image, it might just work and spare yourself the hustle.

**Comment by ThoughtfulDev** [comment]
Yes it was always tested as a non-root user

thanks @waraga2 :)

**Comment by waraga2** [comment]
Yeah sure thing buddy :)
